//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.04 at 12:13:52 PM CET 
//

@org.jboss.seam.annotations.Namespace("http://seamlets.org/cms/cmsconfiguration")
package org.seamlets.cms.configuration;
