//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.24 at 05:16:09 PM CET 
//


package org.seamlets.cms.xsd.template;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Template complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Template">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://jboss.com/products/seam/components}property" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="viewparts" type="{http://seamlets.org/cms/template}ViewParts"/>
 *       &lt;/sequence>
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="importer" use="required" type="{http://jboss.com/products/seam/components}elType" />
 *       &lt;attribute name="confViewId" type="{http://jboss.com/products/seam/components}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Template", namespace = "http://seamlets.org/cms/template", propOrder = {
    "property",
    "viewparts"
})
public class Template {

    protected List<Property> property;
    @XmlElement(namespace = "http://seamlets.org/cms/template", required = true)
    protected ViewParts viewparts;
    @XmlAttribute
    protected String displayName;
    @XmlAttribute(required = true)
    protected String importer;
    @XmlAttribute
    protected List<String> confViewId;

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     * 
     * 
     */
    public List<Property> getProperty() {
        if (property == null) {
            property = new ArrayList<Property>();
        }
        return this.property;
    }

    /**
     * Gets the value of the viewparts property.
     * 
     * @return
     *     possible object is
     *     {@link ViewParts }
     *     
     */
    public ViewParts getViewparts() {
        return viewparts;
    }

    /**
     * Sets the value of the viewparts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewParts }
     *     
     */
    public void setViewparts(ViewParts value) {
        this.viewparts = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the importer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporter() {
        return importer;
    }

    /**
     * Sets the value of the importer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporter(String value) {
        this.importer = value;
    }

    /**
     * Gets the value of the confViewId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the confViewId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfViewId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConfViewId() {
        if (confViewId == null) {
            confViewId = new ArrayList<String>();
        }
        return this.confViewId;
    }

}
