/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itzg_quidsee_proxy_WindowsProxyConfigurator */

#ifndef _Included_com_itzg_quidsee_proxy_WindowsProxyConfigurator
#define _Included_com_itzg_quidsee_proxy_WindowsProxyConfigurator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itzg_quidsee_proxy_WindowsProxyConfigurator
 * Method:    setAutoConfigUrl
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itzg_quidsee_proxy_WindowsProxyConfigurator_setAutoConfigUrl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_itzg_quidsee_proxy_WindowsProxyConfigurator
 * Method:    restoreAutoConfigUrl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itzg_quidsee_proxy_WindowsProxyConfigurator_restoreAutoConfigUrl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
