/*
 * ahorcado.java
 *
 * Created on 28 de mayo de 2012, 22:56
 */
package ahorcado;

import javax.swing.ImageIcon;
import java.util.Random;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author arslupin
 */
public class ahorcado extends javax.swing.JFrame {

    String[] palabras = {"written", "broken", "dream", "been", "analisis", "played", "bug", "married", "done", "eaten", "studying",
        "started", "arrived", "met", "flown", "walked", "working", "raining", "going", "calling"};
    String escogida;
    char[] word;
    char letra;
    int control[] = new int[20];
    int intento = 0;
    int acierto = 0;
    int error = 0;

    /**
     * Creates new form ahorcado
     */
    public ahorcado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAhorcado = new javax.swing.JLabel();
        btnA = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        txt13 = new javax.swing.JTextField();
        txt0 = new javax.swing.JTextField();
        btnI = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnEnie = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblAhorcado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAhorcado.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnA.setText("A");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnB.setText("B");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnD.setText("D");
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        btnJugar.setText("Play");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        txt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setText("  ");
        txt1.setEnabled(false);

        txt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2.setText("  ");
        txt2.setEnabled(false);

        txt4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt4.setText("  ");
        txt4.setEnabled(false);

        txt3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt3.setText("  ");
        txt3.setEnabled(false);

        txt5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt5.setText("  ");
        txt5.setEnabled(false);

        txt6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt6.setText("  ");
        txt6.setEnabled(false);

        txt7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt7.setText("  ");
        txt7.setEnabled(false);

        txt8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt8.setText("  ");
        txt8.setEnabled(false);

        txt9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt9.setText("  ");
        txt9.setEnabled(false);

        txt10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt10.setText("  ");
        txt10.setEnabled(false);

        txt11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt11.setText("  ");
        txt11.setEnabled(false);

        txt12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt12.setText("  ");
        txt12.setEnabled(false);

        txt13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt13.setText("  ");
        txt13.setEnabled(false);

        txt0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt0.setText("  ");
        txt0.setEnabled(false);

        btnI.setText("I");
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });

        btnH.setText("H");
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });

        btnG.setText("G");
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });

        btnF.setText("F");
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });

        btnK.setText("K");
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });

        btnL.setText("L");
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });

        btnM.setText("M");
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });

        btnN.setText("N");
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });

        btnP.setText("P");
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });

        btnQ.setText("Q");
        btnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQActionPerformed(evt);
            }
        });

        btnR.setText("R");
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });

        btnS.setText("S");
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });

        btnU.setText("U");
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        btnV.setText("V");
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });

        btnW.setText("W");
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });

        btnX.setText("X");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btnE.setText("E");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnJ.setText("J");
        btnJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJActionPerformed(evt);
            }
        });

        btnO.setText("O");
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });

        btnT.setText("T");
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        btnY.setText("Y");
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });

        btnZ.setText("Z");
        btnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZActionPerformed(evt);
            }
        });

        btnEnie.setText("Ñ");
        btnEnie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnieActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Juego de ahorcado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnF)
                                        .addComponent(btnA)
                                        .addComponent(btnK))
                                    .addComponent(btnY)
                                    .addComponent(btnT)
                                    .addComponent(btnO))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnG)
                                            .addComponent(btnB)
                                            .addComponent(btnL)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnP, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnU, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnM)
                                            .addComponent(btnH)
                                            .addComponent(btnC)
                                            .addComponent(btnQ)
                                            .addComponent(btnV))
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnJ)
                                            .addComponent(btnE)
                                            .addComponent(btnEnie)
                                            .addComponent(btnS)
                                            .addComponent(btnX)
                                            .addComponent(jLabel1)))
                                    .addComponent(btnZ)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnJugar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt0, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnG, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnJ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnK, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnie, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnW, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnZ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnY, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(447, 447, 447))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
// TODO add your handling code here:
        letra = 'e';
        comparar(letra);
    }//GEN-LAST:event_btnEActionPerformed

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
// TODO add your handling code here:
        letra = 'z';
        comparar(letra);
    }//GEN-LAST:event_btnZActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
// TODO add your handling code here:
        letra = 'y';
        comparar(letra);
    }//GEN-LAST:event_btnYActionPerformed

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
// TODO add your handling code here:
        letra = 'w';
        comparar(letra);
    }//GEN-LAST:event_btnWActionPerformed

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
// TODO add your handling code here:
        letra = 'v';
        comparar(letra);
    }//GEN-LAST:event_btnVActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
// TODO add your handling code here:
        letra = 'u';
        comparar(letra);
    }//GEN-LAST:event_btnUActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
// TODO add your handling code here:
        letra = 't';
        comparar(letra);
    }//GEN-LAST:event_btnTActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
// TODO add your handling code here:
        letra = 's';
        comparar(letra);
    }//GEN-LAST:event_btnSActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
// TODO add your handling code here:
        letra = 'r';
        comparar(letra);
    }//GEN-LAST:event_btnRActionPerformed

    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed
// TODO add your handling code here:
        letra = 'q';
        comparar(letra);
    }//GEN-LAST:event_btnQActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
// TODO add your handling code here:
        letra = 'p';
        comparar(letra);
    }//GEN-LAST:event_btnPActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
// TODO add your handling code here:
        letra = 'o';
        comparar(letra);
    }//GEN-LAST:event_btnOActionPerformed

    private void btnEnieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnieActionPerformed
// TODO add your handling code here:
        letra = 'ñ';
        comparar(letra);
    }//GEN-LAST:event_btnEnieActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
// TODO add your handling code here:
        letra = 'n';
        comparar(letra);
    }//GEN-LAST:event_btnNActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
// TODO add your handling code here:
        letra = 'm';
        comparar(letra);
    }//GEN-LAST:event_btnMActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
// TODO add your handling code here:
        letra = 'l';
        comparar(letra);
    }//GEN-LAST:event_btnLActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
// TODO add your handling code here:
        letra = 'k';
        comparar(letra);
    }//GEN-LAST:event_btnKActionPerformed

    private void btnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJActionPerformed
// TODO add your handling code here:
        letra = 'j';
        comparar(letra);
    }//GEN-LAST:event_btnJActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
// TODO add your handling code here:
        letra = 'i';
        comparar(letra);
    }//GEN-LAST:event_btnIActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
// TODO add your handling code here:
        letra = 'h';
        comparar(letra);
    }//GEN-LAST:event_btnHActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
// TODO add your handling code here:
        letra = 'g';
        comparar(letra);
    }//GEN-LAST:event_btnGActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
// TODO add your handling code here:
        letra = 'f';
        comparar(letra);
    }//GEN-LAST:event_btnFActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
// TODO add your handling code here:
        letra = 'c';
        comparar(letra);
    }//GEN-LAST:event_btnCActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
// TODO add your handling code here:
        letra = 'd';
        comparar(letra);
    }//GEN-LAST:event_btnDActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        letra = 'b';
        comparar(letra);
    }//GEN-LAST:event_btnBActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
// TODO add your handling code here:
        letra = 'a';
        boolean est = comparar(letra);
    }//GEN-LAST:event_btnAActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
// TODO add your handling code here:
        letra = 'x';
        comparar(letra);
    }//GEN-LAST:event_btnXActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
// TODO add your handling code here:
        Random r = new Random();
        int aux = 0;
        int posPal;
        do {
            posPal = r.nextInt(19);
            if (control[posPal] < 1) {
                control[posPal]++;
                escogida = palabras[posPal];
                aux = 1;
                System.out.println(escogida);
            }
        } while (aux == 0);

        limpiar();
        espacios(escogida.length());
        word = escogida.toCharArray();
        lblAhorcado.setIcon(new ImageIcon("/Users/anicavazquez/Documents/ahorcado/src/6.jpg"));
        sonido(efectosSonido.inicio);
        btnJugar.setVisible(false);
    }//GEN-LAST:event_btnJugarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
        for (int x = 0; x < 20; x++) {
            control[x] = 0;
        }
        limpiar();
    }//GEN-LAST:event_formWindowOpened

    private enum efectosSonido {

        noHayJuego, bien, mal, ganaste, perdiste, inicio
    }

    private void sonido(efectosSonido ef) {
        String urlSonido = "";

        try {
            String path = new File(".").getCanonicalPath();
            switch (ef) {
                case noHayJuego:
                    urlSonido = path + "\\src\\audio\\error1.wav";
                    break;
                case bien:
                    urlSonido = path + "\\src\\audio\\bien1.wav";
                    break;
                case mal:
                    urlSonido = path + "\\src\\audio\\mal1.wav";
                    break;
                case ganaste:
                    urlSonido = path + "\\src\\audio\\ganar1.wav";
                    break;
                case perdiste:
                    urlSonido = path + "\\src\\audio\\perder1.wav";
                    break;
                case inicio:
                    urlSonido = path + "\\src\\audio\\inicio1.wav";
                    break;
            }

            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(urlSonido));

            Clip clip = AudioSystem.getClip();
            clip.open(audio);
            clip.start();

        } catch (UnsupportedAudioFileException uae) {
            System.out.println(uae);
        } catch (IOException ioe) {
            System.out.println(ioe);
        } catch (LineUnavailableException lua) {
            System.out.println(lua);
        }
    }

    private boolean comparar(char let) {
        boolean resultado = true;
        try {
            int x = escogida.length();
            int w = 0;
            char aux;

            for (x = 0; x < escogida.length(); x++) {
                aux = word[x];
                if (aux == let) {
                    mostrar(x);
                    w++;
                    acierto++;
                    sonido(efectosSonido.bien);
                }
            }
            if (w < 1) {
                intento++;
                error++;
                sonido(efectosSonido.mal);
                imagen(intento);
                error(let);
                ganar();
                return false;
            }
            acierto(let);
            ganar();
            resultado = true;
        } catch (Exception er) {
            System.out.println("Error 1: No esta en modo de juego");
            sonido(efectosSonido.noHayJuego);
        }
        return resultado;
    }

    private void ganar() {
        if (acierto == escogida.length()) {
            sonido(efectosSonido.ganaste);
            JOptionPane.showMessageDialog(this, "You win, the word is : " + escogida);
            btnJugar.setVisible(true);

            limpiar();
        }
        if (error == 6) {
            sonido(efectosSonido.perdiste);
            JOptionPane.showMessageDialog(this, "You lose the word was : " + escogida);
            btnJugar.setVisible(true);

            limpiar();
        }
    }

    private void imagen(int i) {
        String path = "";
        try {
            path = new File(".").getCanonicalPath();
        } catch (IOException ex) {
            Logger.getLogger(ahorcado.class.getName()).log(Level.SEVERE, null, ex);
        }
        switch (i) {
            case 1:
                lblAhorcado.setIcon(new ImageIcon(path + "\\src\\5.jpg"));
                break;
            case 2:
                lblAhorcado.setIcon(new ImageIcon(path + "\\src\\4.jpg"));
                break;
            case 3:
                lblAhorcado.setIcon(new ImageIcon(path + "\\src\\3.jpg"));
                break;
            case 4:
                lblAhorcado.setIcon(new ImageIcon(path + "\\src\\2.jpg"));
                break;
            case 5:
                lblAhorcado.setIcon(new ImageIcon(path + "\\src\\1.jpg"));
                break;
            case 6:
                lblAhorcado.setIcon(new ImageIcon(path + "\\src\\0.jpg"));
                break;
        }
    }

    private void acierto(char btn) {
        switch (btn) {
            case 'a':
                btnA.setBackground(Color.green);
                break;
            case 'b':
                btnB.setBackground(Color.green);
                break;
            case 'c':
                btnC.setBackground(Color.green);
                break;
            case 'd':
                btnD.setBackground(Color.green);
                break;
            case 'e':
                btnE.setBackground(Color.green);
                break;
            case 'f':
                btnF.setBackground(Color.green);
                break;
            case 'g':
                btnG.setBackground(Color.green);
                break;
            case 'h':
                btnH.setBackground(Color.green);
                break;
            case 'i':
                btnI.setBackground(Color.green);
                break;
            case 'j':
                btnJ.setBackground(Color.green);
                break;
            case 'k':
                btnK.setBackground(Color.green);
                break;
            case 'l':
                btnL.setBackground(Color.green);
                break;
            case 'm':
                btnM.setBackground(Color.green);
                break;
            case 'n':
                btnN.setBackground(Color.green);
                break;
            case 'ñ':
                btnEnie.setBackground(Color.green);
                break;
            case 'o':
                btnO.setBackground(Color.green);
                break;
            case 'p':
                btnP.setBackground(Color.green);
                break;
            case 'q':
                btnQ.setBackground(Color.green);
                break;
            case 'r':
                btnR.setBackground(Color.green);
                break;
            case 's':
                btnS.setBackground(Color.green);
                break;
            case 't':
                btnT.setBackground(Color.green);
                break;
            case 'u':
                btnU.setBackground(Color.green);
                break;
            case 'v':
                btnV.setBackground(Color.green);
                break;
            case 'w':
                btnW.setBackground(Color.green);
                break;
            case 'x':
                btnX.setBackground(Color.green);
                break;
            case 'y':
                btnY.setBackground(Color.green);
                break;
            case 'z':
                btnZ.setBackground(Color.green);
                break;
        }
    }

    private void error(char btn) {
        switch (btn) {
            case 'a':
                btnA.setBackground(Color.red);
                break;
            case 'b':
                btnB.setBackground(Color.red);
                break;
            case 'c':
                btnC.setBackground(Color.red);
                break;
            case 'd':
                btnD.setBackground(Color.red);
                break;
            case 'e':
                btnE.setBackground(Color.red);
                break;
            case 'f':
                btnF.setBackground(Color.red);
                break;
            case 'g':
                btnG.setBackground(Color.red);
                break;
            case 'h':
                btnH.setBackground(Color.red);
                break;
            case 'i':
                btnI.setBackground(Color.red);
                break;
            case 'j':
                btnJ.setBackground(Color.red);
                break;
            case 'k':
                btnK.setBackground(Color.red);
                break;
            case 'l':
                btnL.setBackground(Color.red);
                break;
            case 'm':
                btnM.setBackground(Color.red);
                break;
            case 'n':
                btnN.setBackground(Color.red);
                break;
            case 'ñ':
                btnEnie.setBackground(Color.red);
                break;
            case 'o':
                btnO.setBackground(Color.red);
                break;
            case 'p':
                btnP.setBackground(Color.red);
                break;
            case 'q':
                btnQ.setBackground(Color.red);
                break;
            case 'r':
                btnR.setBackground(Color.red);
                break;
            case 's':
                btnS.setBackground(Color.red);
                break;
            case 't':
                btnT.setBackground(Color.red);
                break;
            case 'u':
                btnU.setBackground(Color.red);
                break;
            case 'v':
                btnV.setBackground(Color.red);
                break;
            case 'w':
                btnW.setBackground(Color.red);
                break;
            case 'x':
                btnX.setBackground(Color.red);
                break;
            case 'y':
                btnY.setBackground(Color.red);
                break;
            case 'z':
                btnZ.setBackground(Color.red);
                break;
        }
    }

    private void mostrar(int y) {
        switch (y) {
            case 0:
                txt0.setText(String.valueOf(word[y]));
                break;
            case 1:
                txt1.setText(String.valueOf(word[y]));
                break;
            case 2:
                txt2.setText(String.valueOf(word[y]));
                break;
            case 3:
                txt3.setText(String.valueOf(word[y]));
                break;
            case 4:
                txt4.setText(String.valueOf(word[y]));
                break;
            case 5:
                txt5.setText(String.valueOf(word[y]));
                break;
            case 6:
                txt6.setText(String.valueOf(word[y]));
                break;
            case 7:
                txt7.setText(String.valueOf(word[y]));
                break;
            case 8:
                txt8.setText(String.valueOf(word[y]));
                break;
            case 9:
                txt9.setText(String.valueOf(word[y]));
                break;
            case 10:
                txt10.setText(String.valueOf(word[y]));
                break;
            case 11:
                txt11.setText(String.valueOf(word[y]));
                break;
            case 12:
                txt12.setText(String.valueOf(word[y]));
                break;
            case 13:
                txt13.setText(String.valueOf(word[y]));
                break;
        }
    }

    private void limpiar() {
        txt0.setVisible(false);
        txt1.setVisible(false);
        txt2.setVisible(false);
        txt3.setVisible(false);
        txt4.setVisible(false);
        txt5.setVisible(false);
        txt6.setVisible(false);
        txt7.setVisible(false);
        txt8.setVisible(false);
        txt9.setVisible(false);
        txt10.setVisible(false);
        txt11.setVisible(false);
        txt12.setVisible(false);
        txt13.setVisible(false);
        txt0.setText("");
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txt5.setText("");
        txt6.setText("");
        txt7.setText("");
        txt8.setText("");
        txt9.setText("");
        txt10.setText("");
        txt11.setText("");
        txt12.setText("");
        txt13.setText("");
        btnA.setBackground(Color.white);
        btnB.setBackground(Color.white);
        btnC.setBackground(Color.white);
        btnD.setBackground(Color.white);
        btnE.setBackground(Color.white);
        btnF.setBackground(Color.white);
        btnG.setBackground(Color.white);
        btnH.setBackground(Color.white);
        btnI.setBackground(Color.white);
        btnJ.setBackground(Color.white);
        btnK.setBackground(Color.white);
        btnL.setBackground(Color.white);
        btnM.setBackground(Color.white);
        btnN.setBackground(Color.white);
        btnEnie.setBackground(Color.white);
        btnO.setBackground(Color.white);
        btnP.setBackground(Color.white);
        btnQ.setBackground(Color.white);
        btnR.setBackground(Color.white);
        btnS.setBackground(Color.white);
        btnT.setBackground(Color.white);
        btnU.setBackground(Color.white);
        btnV.setBackground(Color.white);
        btnW.setBackground(Color.white);
        btnX.setBackground(Color.white);
        btnY.setBackground(Color.white);
        btnZ.setBackground(Color.white);
        acierto = 0;
        error = 0;
        intento = 0;
    }

    private void espacios(int x) {
        txt0.setVisible(true);
        txt1.setVisible(true);
        if (x >= 3) {
            txt2.setVisible(true);
        }
        if (x >= 4) {
            txt3.setVisible(true);
        }
        if (x >= 5) {
            txt4.setVisible(true);
        }
        if (x >= 6) {
            txt5.setVisible(true);
        }
        if (x >= 7) {
            txt6.setVisible(true);
        }
        if (x >= 8) {
            txt7.setVisible(true);
        }
        if (x >= 9) {
            txt8.setVisible(true);
        }
        if (x >= 10) {
            txt9.setVisible(true);
        }
        if (x >= 11) {
            txt10.setVisible(true);
        }
        if (x >= 12) {
            txt11.setVisible(true);
        }
        if (x >= 13) {
            txt12.setVisible(true);
        }
        if (x >= 14) {
            txt13.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ahorcado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEnie;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAhorcado;
    private javax.swing.JTextField txt0;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
