//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.24 at 05:16:09 PM CET 
//


package org.seamlets.cms.xsd.template;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://jboss.com/products/seam/components}component"/>
 *         &lt;element ref="{http://jboss.com/products/seam/components}factory"/>
 *         &lt;element ref="{http://jboss.com/products/seam/components}event"/>
 *         &lt;element ref="{http://jboss.com/products/seam/components}import"/>
 *         &lt;any/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "componentOrFactoryOrEvent"
})
@XmlRootElement(name = "components")
public class Components {

    @XmlElementRefs({
        @XmlElementRef(name = "factory", namespace = "http://jboss.com/products/seam/components", type = Factory.class),
        @XmlElementRef(name = "event", namespace = "http://jboss.com/products/seam/components", type = Event.class),
        @XmlElementRef(name = "import", namespace = "http://jboss.com/products/seam/components", type = JAXBElement.class),
        @XmlElementRef(name = "component", namespace = "http://jboss.com/products/seam/components", type = Component.class)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> componentOrFactoryOrEvent;

    /**
     * Gets the value of the componentOrFactoryOrEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the componentOrFactoryOrEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponentOrFactoryOrEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Factory }
     * {@link Component }
     * {@link Event }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getComponentOrFactoryOrEvent() {
        if (componentOrFactoryOrEvent == null) {
            componentOrFactoryOrEvent = new ArrayList<Object>();
        }
        return this.componentOrFactoryOrEvent;
    }

}
