//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.04 at 12:13:52 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jboss.com/products/seam/components", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.seamlets.cms.xsd.seam.components;
